

    // BE ABLE TO WRITE THE SAME FUNCTION DIFFERENT WAYS IN JS

    // PASS FUNCTIONS AS ARGUMENTS TO OTHER FUNCTIONS AND CALL THEM AS CALLBACKS

    // KNOW HOW CLOSURES WORK

    // UNDERSTAND PROTOTYPICAL INHERITENCE 

        // MONKEY PATCH IN JS
        

    